name: hr_perfect
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.19.0
  uuid: ^4.0.0
  image_picker: ^1.0.4
  shared_preferences: ^2.2.1
  google_fonts: ^6.1.0
  http: ^1.1.0
  logger: ^2.0.0
  flutter_local_notifications: ^18.0.1
  crypto: ^3.0.3
  table_calendar: ^3.1.2
  permission_handler: ^11.0.1 
  cupertino_icons: ^1.0.8
  get: ^4.6.5
  lucide_icons: ^0.257.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/img/logo.png"
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1 

flutter:
  uses-material-design: true

  assets:
   - lib/assets/img/WhatsApp_Image_2026-01-02_at_16.12.09-removebg-preview.png
   - lib/assets/img/logo.png